#Sintaxe básica do Pytorch
Assim como o Numpy, o Pytorch é uma biblioteca de processamento vetorial/ matricial/ tensorial. Operações sobre os tensores do Pytorch possuem sintaxa consideravelmente parecida com operações sobre tensores do Numpy.

Para mais informações sobre tensores em Pytorch, consulte a documentação:
https://pytorch.org/docs/stable/tensors.html

##Tipos de tensores
Você pode criar tensores do PyTorch de inúmeras formas! Vamos ver primeiro os tipos de tensores que estão ao nosso dispor. Para isso, vamos converter listas comuns do Python em tensors do PyTorch.

Note que a impressão de tensores dos tipos float32 e int64 não vêm acompanhadas do parâmetro de tipo dtype, visto que se tratam dos tipos padrão trabalhados pelo PyTorch.

In [5]:
import torch
import numpy as np

lista = [[1,2,3],
         [4,5,6]]

tns= torch.Tensor(lista)#ele naturalmente converte pra float,mas você pode ser preciso, como abaixo,mas há vários tipos
print(tns.dtype)
print(tns)

tns= torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

tns= torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

tns= torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


##Outas formas de instancias tensores
**A partir de arrays Numpy**

*torch.from_numpy()*

Ele preserva o tipo anterior dos dados

In [12]:
arr = np.random.rand(3,4)
arr2 = arr.astype(int)
tns = torch.from_numpy(arr)
tns2= torch.from_numpy(arr2)


print(arr2)
print(arr2.dtype)
print()

print(tns2)
print(tns2.dtype)
print()

print(arr)
print(arr.dtype)
print()

print(tns)
print(tns.dtype)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
torch.int64

[[0.85153364 0.21641781 0.23369059 0.89853627]
 [0.66937803 0.60442616 0.10900173 0.19891401]
 [0.1438584  0.18237098 0.74570533 0.82717983]]
float64

tensor([[0.8515, 0.2164, 0.2337, 0.8985],
        [0.6694, 0.6044, 0.1090, 0.1989],
        [0.1439, 0.1824, 0.7457, 0.8272]], dtype=torch.float64)
torch.float64


##Tensores inicializados
Essas funções recebem como parâmetro o tamanho o tamanho de cada dimensão do tensor. Aqui vamos conhecer as seguintes funções:

*torch.ones()* - > Cria um tensor preenchido com uns.

*torch.zeros()* -> Cria um tensor prenchido com zero.

*torch.randn()* -> Cria um tensor preenchido com números aleatórios a partir de uma distribuição normal.

In [13]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[-1.0979, -0.2189,  1.0250],
        [-0.6968, -0.5629,  0.1636],
        [-0.3560, -0.3159,  1.2593]])


##Tensor para array numpy

In [15]:
print(type(tnsr))

arr = tnsr.data.numpy()

print(arr)

<class 'torch.Tensor'>
[[-1.0978917  -0.21894245  1.0250291 ]
 [-0.6968106  -0.56291705  0.16364293]
 [-0.3560119  -0.3159333   1.2592673 ]]


##Indexação
De posse dessa informação, a indexação é feita de forma similar a arrays Numpy, atráves de sintaxa de colchetes [ ].

In [17]:
print(tnsr)

tnsr[0,2] = -10 #mudando os valores do tensor

print('')
print(tnsr)

print()
print(tnsr[:,2])#todas as linhas,mas só da coluna dois

tensor([[ -1.0979,  -0.2189, -10.0000],
        [ -0.6968,  -0.5629,   0.1636],
        [ -0.3560,  -0.3159,   1.2593]])

tensor([[ -1.0979,  -0.2189, -10.0000],
        [ -0.6968,  -0.5629,   0.1636],
        [ -0.3560,  -0.3159,   1.2593]])

tensor([-10.0000,   0.1636,   1.2593])


##Operações com tensores

Afunção ```.item( )``` utilizada anteriormente extrai o número de um tgensor que possui um único valor, permitindo realizar as operações numéricas do Python.
Caso o item não seja extraído, operações que envolvam tensores vão retornar novos tensores.

Vale ressaltar também que operações entre tensores são realizadas **ponto a ponto**, operando cada elemento ```(i, j)``` do tensor ```t1```, com o elemento ```(i, j)``` do tensor ```t2```.

In [25]:
tns = tnsr[0:2, :] #foi pra arrumar a dimensão,mas já foi

print(tns.shape)
print(tns1.shape)
print()

print(tns)
print(tns1)

print()
print(tns+tns1)
print()

print(tns*tns1)
print()
print(torch.mm(tns1,tns.T))

torch.Size([2, 3])
torch.Size([2, 3])

tensor([[ -1.0979,  -0.2189, -10.0000],
        [ -0.6968,  -0.5629,   0.1636]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[-0.0979,  0.7811, -9.0000],
        [ 0.3032,  0.4371,  1.1636]])

tensor([[ -1.0979,  -0.2189, -10.0000],
        [ -0.6968,  -0.5629,   0.1636]])

tensor([[-11.3168,  -1.0961],
        [-11.3168,  -1.0961]])


##Função .size( ) e .view( )
Uma operação **importantíssima** na manipilação de tensores para Deep Learning é a reorganização das suas dimensões. Dessa forma podem, por exemplo **linearizar um tensor n-dimensional.**

In [30]:
tns = torch.randn(2,2,3)#isso é um cubo
print(tns)
print()

print(tns.size())
print()
tns = tns.view(12) # ele foi achatado em uma dimensão só. poderiamos usar .view(-1), também seria achatado
print(tns)
print()

tns = tns.view(-1) # .view(-1), também seria achatado
print(tns)
print()

tns = tns.view(4,3) # 
print(tns)
print()

tns = tns.view(tns.size(0), -1) # é o mais comum, eu mantenho a primeira dimensão e achato o resto
print(tns)

tensor([[[-1.0502, -0.7507, -0.1081],
         [ 0.2673,  0.3129, -0.5546]],

        [[ 0.8821, -0.1215, -0.2179],
         [-1.4147, -0.1557,  0.8162]]])

torch.Size([2, 2, 3])

tensor([-1.0502, -0.7507, -0.1081,  0.2673,  0.3129, -0.5546,  0.8821, -0.1215,
        -0.2179, -1.4147, -0.1557,  0.8162])

tensor([-1.0502, -0.7507, -0.1081,  0.2673,  0.3129, -0.5546,  0.8821, -0.1215,
        -0.2179, -1.4147, -0.1557,  0.8162])

tensor([[-1.0502, -0.7507, -0.1081],
        [ 0.2673,  0.3129, -0.5546],
        [ 0.8821, -0.1215, -0.2179],
        [-1.4147, -0.1557,  0.8162]])


###Exercícios
Nesta aula nos familiarizamos com o ambiente do Google Colab à medida que introduzimos a sintaxe básica do PyTorch para manipulação de tensores. Para trabalhar com redes neurais, a sua principal preocupação em relação aos tensores é garantir que sua dimensionalidade seja consistente com a operação que se deseja realizar.

Pensando nisso, crie um tensor aleatório tns1 com a dimensionalidade 7 x 7 x 3 e um outro tensor aleatório tns2 de 147 x 1. Modificando apenas tns1 some os dois tensores.

In [3]:
tns1 = torch.randn(7,7,3)
print(tns1)
print()

tns2 = torch.randn(147,1)
print(tns2)
print()

tns1= tns1.view(-1,1)
print(tns1+tns2)

tensor([[[-0.1086,  0.2686, -0.5262],
         [ 1.5064, -0.3271,  0.5262],
         [-0.4352,  0.8846, -0.6504],
         [ 0.1848,  1.3958, -0.6652],
         [ 0.4572,  0.1612, -0.8047],
         [-2.1675,  0.0606,  0.0188],
         [ 0.0691, -0.0879,  1.3633]],

        [[ 0.3006, -0.0909, -0.8073],
         [-0.4640, -0.8353, -0.7043],
         [-0.2926, -0.3293,  0.4867],
         [ 0.3140, -0.0559, -0.4851],
         [ 1.4644, -0.3528,  0.4854],
         [-0.2644, -0.8133, -0.6776],
         [ 0.1915,  0.1843,  1.0513]],

        [[-0.8160,  0.7080, -1.2788],
         [ 0.5652, -0.1526, -1.5940],
         [-0.2878,  0.8206,  1.3026],
         [-1.8924, -0.0202, -1.2207],
         [-0.2164,  0.1719, -1.2324],
         [-0.3513,  0.4038, -0.9650],
         [-0.3931, -0.2070, -1.1340]],

        [[ 0.6371, -0.0970, -1.0627],
         [-0.0460, -0.9997, -0.5690],
         [-0.9556,  0.6509, -1.4445],
         [-0.0112, -0.0514,  0.5998],
         [ 0.9820,  1.5744,  0.1966],
      

##GPU Cast
Para que o seu script dê suporte a infraestruturas com e sem GPU, é importante definir o dispositivo no início do seu código de acordo com a verificação apresentada a seguir. Essa definição de dispositivo será utilizada toda vez que precisamos subir valores na GPU, como os pesos da rede, os gradientes, etc.

Toda vez que tu for usar o GPU precisa mexer nas configurações e jogar os dados lá

In [1]:
import torch #pra criar modelos robustos a gente precisa jogar na GPU

tns= torch.randn(10)

if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

print(device)

tns = tns.to(device)
print(tns)

cuda
tensor([ 1.1542,  0.3927,  0.2003, -0.5309, -0.8991,  0.6546,  1.4618, -0.3219,
        -2.3585,  1.2743], device='cuda:0')


##Pra saber mais
Nesta aula, tivemos uma visão geral de manipulação de tensores, mas ainda há um universo de possibilidades que pode ser encontrado na 
[documentação do objeto Tensor do PyTorch.](https://pytorch.org/docs/stable/tensors.html)


Uma operação muito útil, que não faz parte diretamente do módulo de tensores, é a concatenação. Modelos mais complexos, que envolvem fusão de informação, ou entradas que precisam ser manipuladas antes de ser enviadas para a rede, se beneficiam muito dessa operação. Para isso, o pacote ```torch``` traz a  [função cat](https://pytorch.org/docs/stable/torch.html#torch.cat) que tem o seguinte padrão:

```tns_out = torch.cat( (tns1, tns2), dim=0 )```
Ou seja, a função recebe um objeto tipo tupla contendo o conjunto de tensores a ser concatenados, seguido da dimensão de concatenação. Os tensores devem ter dimensões idênticas, exceto na dimensão de concatenação.

Outras operações para combinar múltiplos tensores pode ser encontrada [nessa parte da documentação.](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

Para trabalhar com Deep Learning no PyTorch é preciso dominar a arte de manipular tensores e transformá-los da forma que o problema necessitar. Explore amplamente a documentação do [pacote torch](https://pytorch.org/docs/stable/torch.html) e encontrará funções como
```torch.queeze( )``` 
 e ```torch.unsqueeze( )``` que, respectivamente, removem e adicionam dimensões de tamanho 1. Essas e outras funções vão facilitar muito o seu trabalho e te tornar um mestre na arte dos tensores!